package com.NobodyKnows.chatlayoutview.Constants;

public enum  MessageType {
    IMAGE, //UPLOAD REMAING
    VIDEO, //UPLOAD REMAING
    AUDIO, //UPLOAD REMAING
    RECORDING, //UPLOAD REMAING
    DOCUMENT, //UPLOAD REMAING

    TEXT, //DONE
    GIF, //DONE
    CONTACT_SINGLE, //DONE
    CONTACT_MULTIPLE, //DONE
    DATE, //DONE
    STICKER, //DONE
    INFO, //DONE
    WARNING, //DONE
    LINK, //DONE

//    MAP, //NOT REQUIRED

    BLOCKED,
    UNBLOCKED,
    UNFREIND,
    SECURITY_KEY_CHANGED,
    MISSED_AUDIO_CALL,
    MISSED_VIDEO_CALL
}
